// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloDB;

namespace ModeloDB.Migrations
{
    [DbContext(typeof(PruebaDB))]
    [Migration("20220124153942_CargaIni")]
    partial class CargaIni
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ModeloPrueba.Entidades.staff", b =>
                {
                    b.Property<int>("staffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("address_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_update")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("storeId")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("staffId");

                    b.ToTable("staffs");
                });

            modelBuilder.Entity("ModeloPrueba.Entidades.store", b =>
                {
                    b.Property<int>("storeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_update")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("manager_staff_id")
                        .HasColumnType("int");

                    b.HasKey("storeId");

                    b.HasIndex("manager_staff_id")
                        .IsUnique();

                    b.ToTable("stores");
                });

            modelBuilder.Entity("ModeloPrueba.Entidades.store", b =>
                {
                    b.HasOne("ModeloPrueba.Entidades.staff", "staffstore")
                        .WithOne("storestaff")
                        .HasForeignKey("ModeloPrueba.Entidades.store", "manager_staff_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("staffstore");
                });

            modelBuilder.Entity("ModeloPrueba.Entidades.staff", b =>
                {
                    b.Navigation("storestaff");
                });
#pragma warning restore 612, 618
        }
    }
}
